pip install scikit-learn

In [1]:
import sklearn
import pandas as pd
import numpy as np

print(sklearn.__version__)

1.0.2


In [5]:
from sklearn.datasets import load_iris

iris = load_iris()

In [6]:
type(iris)

sklearn.utils.Bunch

In [7]:
iris.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [13]:
iris_df = pd.DataFrame(iris.data, columns = iris.feature_names) ; iris_df.head(5)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [17]:
iris_df['label'] = iris.target ; iris_df.head() # target label이 될 값

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   label  
0      0  
1      0  
2      0  
3      0  
4      0

In [18]:
from sklearn.model_selection import train_test_split # train test 분리해주는 모듈

In [20]:
type(iris.data)

numpy.ndarray

In [21]:
iris_data = iris.data
iris_label = iris.target

In [22]:
x_train, x_test, y_train, y_test = train_test_split(c)

In [24]:
len(x_train)

120

In [26]:
len(x_test)

30

In [27]:
from sklearn.tree import DecisionTreeClassifier

In [28]:
df_clf = DecisionTreeClassifier(random_state = 7)
df_clf.fit(x_train, y_train)

DecisionTreeClassifier(random_state=7)

In [29]:
from sklearn.metrics import accuracy_score

In [30]:
pred = df_clf.predict(x_test)
ac_score = accuracy_score(y_test, pred)

In [31]:
ac_score

0.9

In [32]:
from sklearn.preprocessing import LabelEncoder # 명목형 변수를 숫자로 변환한다

In [33]:
items = ['TV', '냉장고', '전자레인지', '컴퓨터', 'TV', '냉장고', '컴퓨터', '컴퓨터']

In [34]:
encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)

print(labels)
print(encoder.classes_)

[0 1 2 3 0 1 3 3]
['TV' '냉장고' '전자레인지' '컴퓨터']


In [37]:
labels = labels.reshape(-1,1)

In [38]:
from sklearn.preprocessing import OneHotEncoder

In [39]:
oh_encoder = OneHotEncoder()
oh_encoder.fit(labels)
oh_labels = oh_encoder.transform(labels)

In [41]:
oh_labels.toarray()

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.]])

In [43]:
oh_labels.shape

(8, 4)

In [45]:
item_df = pd.DataFrame({'item' : items})
item_df

item
0     TV
1    냉장고
2  전자레인지
3    컴퓨터
4     TV
5    냉장고
6    컴퓨터
7    컴퓨터

In [46]:
pd.get_dummies(item_df) # pandas 원핫인코더, 명목형도 바로 변환이 가능하다

item_TV  item_냉장고  item_전자레인지  item_컴퓨터
0        1         0           0         0
1        0         1           0         0
2        0         0           1         0
3        0         0           0         1
4        1         0           0         0
5        0         1           0         0
6        0         0           0         1
7        0         0           0         1

In [50]:
iris = load_iris()
iris_data = iris.data
iris_df = pd.DataFrame(data = iris_data, columns = iris.feature_names)

In [53]:
iris_df.describe()

sepal length (cm)  sepal width (cm)  petal length (cm)  \
count         150.000000        150.000000         150.000000   
mean            5.843333          3.057333           3.758000   
std             0.828066          0.435866           1.765298   
min             4.300000          2.000000           1.000000   
25%             5.100000          2.800000           1.600000   
50%             5.800000          3.000000           4.350000   
75%             6.400000          3.300000           5.100000   
max             7.900000          4.400000           6.900000   

       petal width (cm)  
count        150.000000  
mean           1.199333  
std            0.762238  
min            0.100000  
25%            0.300000  
50%            1.300000  
75%            1.800000  
max            2.500000

In [54]:
from sklearn.preprocessing import StandardScaler # 표준화

In [55]:
scaler = StandardScaler()
scaler.fit(iris_df)
iris_scaled = scaler.transform(iris_df)
iris_df_scaled = pd.DataFrame(data = iris_scaled, columns=iris.feature_names)

In [56]:
iris_df_scaled.describe()

sepal length (cm)  sepal width (cm)  petal length (cm)  \
count       1.500000e+02      1.500000e+02       1.500000e+02   
mean       -1.468455e-15     -1.823726e-15      -1.610564e-15   
std         1.003350e+00      1.003350e+00       1.003350e+00   
min        -1.870024e+00     -2.433947e+00      -1.567576e+00   
25%        -9.006812e-01     -5.923730e-01      -1.226552e+00   
50%        -5.250608e-02     -1.319795e-01       3.364776e-01   
75%         6.745011e-01      5.586108e-01       7.627583e-01   
max         2.492019e+00      3.090775e+00       1.785832e+00   

       petal width (cm)  
count      1.500000e+02  
mean      -9.473903e-16  
std        1.003350e+00  
min       -1.447076e+00  
25%       -1.183812e+00  
50%        1.325097e-01  
75%        7.906707e-01  
max        1.712096e+00

In [57]:
from sklearn.preprocessing import MinMaxScaler

In [59]:
scaler = MinMaxScaler()
scaler.fit(iris_df)
iris_scaled = scaler.transform(iris_df)
iris_df_scaled = pd.DataFrame(data = iris_scaled, columns=iris.feature_names)

In [60]:
iris_df_scaled.describe()

sepal length (cm)  sepal width (cm)  petal length (cm)  \
count         150.000000        150.000000         150.000000   
mean            0.428704          0.440556           0.467458   
std             0.230018          0.181611           0.299203   
min             0.000000          0.000000           0.000000   
25%             0.222222          0.333333           0.101695   
50%             0.416667          0.416667           0.567797   
75%             0.583333          0.541667           0.694915   
max             1.000000          1.000000           1.000000   

       petal width (cm)  
count        150.000000  
mean           0.458056  
std            0.317599  
min            0.000000  
25%            0.083333  
50%            0.500000  
75%            0.708333  
max            1.000000

In [61]:
################ 여기까지 내용을 이용한 분석해보자 #########################

In [62]:
import sklearn
import pandas as pd
import numpy as np

In [63]:
iris = load_iris()

In [67]:
iris_df = pd.DataFrame(data = iris.data, columns = iris.feature_names) ; iris_df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [68]:
from sklearn.model_selection import train_test_split

In [69]:
iris_data = iris.data
iris_label = iris.target

In [71]:
x_train, x_test, y_train, y_test = train_test_split(iris_data, iris_label, test_size = 0.3, random_state = 10)

In [73]:
from sklearn.tree import DecisionTreeClassifier

In [74]:
df_clf = DecisionTreeClassifier()

In [75]:
df_clf.fit(x_train, y_train)

DecisionTreeClassifier()

In [76]:
from sklearn.metrics import accuracy_score

In [77]:
pred = df_clf.predict(x_test)
accuracy_score(y_test,pred)

0.9777777777777777

In [78]:
# sclaer 사용

In [81]:
from sklearn.preprocessing import MinMaxScaler

In [82]:
iris_df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [86]:
mms = MinMaxScaler()
mms.fit(iris_df)
scale_iris_df = mms.transform(iris_df) # scle하면 nndarray로 변환됨

array([[0.22222222, 0.625     , 0.06779661, 0.04166667],
       [0.16666667, 0.41666667, 0.06779661, 0.04166667],
       [0.11111111, 0.5       , 0.05084746, 0.04166667],
       [0.08333333, 0.45833333, 0.08474576, 0.04166667],
       [0.19444444, 0.66666667, 0.06779661, 0.04166667],
       [0.30555556, 0.79166667, 0.11864407, 0.125     ],
       [0.08333333, 0.58333333, 0.06779661, 0.08333333],
       [0.19444444, 0.58333333, 0.08474576, 0.04166667],
       [0.02777778, 0.375     , 0.06779661, 0.04166667],
       [0.16666667, 0.45833333, 0.08474576, 0.        ],
       [0.30555556, 0.70833333, 0.08474576, 0.04166667],
       [0.13888889, 0.58333333, 0.10169492, 0.04166667],
       [0.13888889, 0.41666667, 0.06779661, 0.        ],
       [0.        , 0.41666667, 0.01694915, 0.        ],
       [0.41666667, 0.83333333, 0.03389831, 0.04166667],
       [0.38888889, 1.        , 0.08474576, 0.125     ],
       [0.30555556, 0.79166667, 0.05084746, 0.125     ],
       [0.22222222, 0.625     ,

In [87]:
scale_iris_df

array([[0.22222222, 0.625     , 0.06779661, 0.04166667],
       [0.16666667, 0.41666667, 0.06779661, 0.04166667],
       [0.11111111, 0.5       , 0.05084746, 0.04166667],
       [0.08333333, 0.45833333, 0.08474576, 0.04166667],
       [0.19444444, 0.66666667, 0.06779661, 0.04166667],
       [0.30555556, 0.79166667, 0.11864407, 0.125     ],
       [0.08333333, 0.58333333, 0.06779661, 0.08333333],
       [0.19444444, 0.58333333, 0.08474576, 0.04166667],
       [0.02777778, 0.375     , 0.06779661, 0.04166667],
       [0.16666667, 0.45833333, 0.08474576, 0.        ],
       [0.30555556, 0.70833333, 0.08474576, 0.04166667],
       [0.13888889, 0.58333333, 0.10169492, 0.04166667],
       [0.13888889, 0.41666667, 0.06779661, 0.        ],
       [0.        , 0.41666667, 0.01694915, 0.        ],
       [0.41666667, 0.83333333, 0.03389831, 0.04166667],
       [0.38888889, 1.        , 0.08474576, 0.125     ],
       [0.30555556, 0.79166667, 0.05084746, 0.125     ],
       [0.22222222, 0.625     ,

In [92]:
x_train, x_test, y_train, y_test = train_test_split(scale_iris_df, iris_label, test_size = 0.3, random_state = 11)

In [93]:
df_clf.fit(x_train, y_train)

DecisionTreeClassifier()

In [94]:
pred = df_clf.predict(x_test)
accuracy_score(y_test,pred)

0.9111111111111111